import { amenities, reviews, services, site } from '../content/site'

export function HomePage() {
  const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`
  return <>
    <section className="hero" id="top"><div className="hero-copy"><p className="kicker">Барбершоп · Москва · ЗИЛ</p><img className="hero-logo" src={asset('media/logo.png')} alt="Gonor" /><h1>Стрижка,<br /><em>которая</em> держит форму.</h1><p className="hero-lede">{site.description}</p><div className="hero-actions"><a className="button button-red" href={site.bookingUrl} target="_blank" rel="noreferrer">Записаться онлайн <span>↗</span></a><a className="under-link" href="#services">Смотреть услуги <span>↓</span></a></div></div><div className="hero-visual"><img src={asset('media/source-interior.jpg')} alt="Интерьер барбершопа Gonor" /><span className="hero-stamp">GONOR<br /><b>МУЖСКАЯ<br />СТРИЖКА</b></span><span className="hero-index">01 / 04</span></div></section>
    <section className="proof-strip"><div><strong>5,0</strong><span>рейтинг<br />на Яндекс Картах</span></div><div><strong>132</strong><span>оценки<br />гостей</span></div><div><strong>22:00</strong><span>закрываемся<br />каждый день</span></div><a href={site.mapsUrl} target="_blank" rel="noreferrer">Хорошее место 2026 <span>↗</span></a></section>
    <section className="services section" id="services"><div className="section-top"><p className="kicker">01 / Услуги</p><p className="section-note">Без лишних слов.<br />Сначала слушаем, потом стрижём.</p></div><div className="service-layout"><h2>Точность<br /><span>в деталях.</span></h2><div className="service-list">{services.map((service, index) => <article className="service-row" key={service.title}><span className="service-number">0{index + 1}</span><div><h3>{service.title}</h3><p>{service.detail}</p></div><strong>{service.price}</strong></article>)}</div></div><p className="price-note">Актуальную стоимость уточняйте при записи. Полный прайс можно получить у администратора.</p></section>
    <section className="atmosphere"><div className="atmosphere-image"><img src={asset('media/gallery-space.jpg')} alt="Пространство Gonor" /></div><div className="atmosphere-copy"><p className="kicker">02 / Место</p><h2>Не просто<br /><em>зайти</em> и выйти.</h2><p>Второй этаж — зал ожидания с телевизором и приставкой. Можно приехать заранее, спокойно выдохнуть и не торопиться.</p><div className="amenities">{amenities.map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="reviews section" id="reviews"><div className="section-top"><p className="kicker">03 / Отзывы</p><a className="under-link" href={site.mapsUrl} target="_blank" rel="noreferrer">Все отзывы <span>↗</span></a></div><div className="review-heading"><h2>Гости<br /><em>возвращаются.</em></h2><div className="review-score"><strong>5,0</strong><span>108 отзывов</span></div></div><div className="review-grid">{reviews.map((review) => <blockquote key={review.author}><p>“{review.quote}”</p><cite>{review.author}</cite></blockquote>)}</div></section>
    <section className="contact" id="contacts"><div className="contact-main"><p className="kicker">04 / Контакты</p><h2>До встречи<br /><em>в Gonor.</em></h2><a className="button button-red" href={site.bookingUrl} target="_blank" rel="noreferrer">Записаться онлайн <span>↗</span></a></div><div className="contact-details"><div><span>Адрес</span><a href={site.routeUrl} target="_blank" rel="noreferrer">{site.contact.address} ↗</a></div><div><span>Телефон</span><a href={site.contact.phoneHref}>{site.contact.phone}</a></div><div><span>Режим работы</span><p>{site.contact.hours}</p></div><a className="whatsapp" href={site.whatsappUrl} target="_blank" rel="noreferrer">Написать в WhatsApp ↗</a></div></section>
  </>
}
